version: "3.2"

services:
  php-fpm:
    image: webdevops/php-dev:7.4
    hostname: php-fpm
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PHP_IDE_CONFIG=serverName=docker-server
      - PHP_ENABLE_XDEBUG=1
    extra_hosts:
      - "host.docker.internal:192.168.43.105"
    depends_on:
      - mysql
  nginx:
    container_name: nginx-server
    image: webdevops/nginx
    ports:
      - 90:80
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/web
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=github_observer
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret